import 'package:get/get.dart';

class MyLocale implements Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "ar": {
          "10": "مرحبا",
          "11": "مكتبة جامعة الناصر",
          "12": "اسم المستخدم",
          "13": "ادخل اسم المستخدم",
          "14": " كلمة السر",
          "15": "ادخل كلمة السر",
          "16": "دخول",
          "17": "اسم المستخدم غير صحيح",
          "18": "كلمة السر غير صحيح",
          "21": "الكتب",
          "20": "عرض الكل",
          "22": "الكتب الالكترونية",
          "23": "المشاريع ",
          "30": "مكتبة الكتب ",
          "31": "تفاصيل الكتب ",
          "32": " اسم الكتاب ",
          "33": " الرقم العالمي ",
          "34": " اسم الناشر ",
          "35": " بيانات الناشر ",
          "36": " اللغة ",
          "37": " عدد النسخ الموجك ",
          "38": "  تاريخ النشر ",
          "40": "مكتبة الكتب الالكترونية ",
          "41": "تفاصيل الكتاب ",
          "42": "اسم الكتاب ",
          "43": " الرقم العالمي ",
          "44": "اللغة ",
          "45": "اسم الناشر ",
          "46": " بيانات الناشر",
          "47": "تاريخ النشر ",
          "50": "مكتبة المشاريغ",
          "51": "تفاصيل المشروع",
          "52": "اسم المشروع",
          "53": "اللغة",
          "54": " المشرف",
          "55": "عدد النسخ",
          "70": "الاعدادات",
          "71": "مشاركه التطبيق",
          "72": "عني",
          "100": "تعديل الملف الشخصي",
          "101": "مشاركه التطبيق",
          "102": "خروج",
        },
        "en": {
          "10": "Welcome",
          "11": "IN  Yniversity Library",
          "12": "username",
          "13": "Enter username",
          "14": "passWord",
          "15": "Enter password",
          "16": "SgIn",
          "17": "Invalid Username",
          "18": "Invalid Password",
          "21": "Book",
          "20": "See_All",
          "22": "Ebook",
          "23": "Project",
          "30": "Librare Book  ",
          "31": "Detils Book : ",
          "32": "Name Book : ",
          "33": "Issn Book : ",
          "34": "Author Name : ",
          "35": "Buplisher Data : ",
          "36": "Languge : ",
          "37": "Number copy : ",
          "38": " Date of publisher :",
          "40": " Library EBook ",
          "41": "Detils  of Ebook ",
          "42": " Name Ebook ",
          "43": " Issn Ebook ",
          "44": " Languge ",
          "45": " Author Name ",
          "46": " publisher Data  ",
          "47": " year publisher  ",
          "50": " Librare Project ",
          "51": "Details Project ",
          "52": "Name Project :  ",
          "53": " Langug  ",
          "54": " supervisor  ",
          "55": "quantity  ",
          "70": "Setteng  ",
          "71": " Shera  ",
          "72": " About  ",
          "100": "Edit profile ",
          "101": "Share",
          "102": "Logout"
          // "11": "Location",
          // "12": "Email",
          // "13": "Phone",
          // "14": "About Me",
          // "15":"Home",
          // "16":"Setting",
          // "17":"about",
          // "18":"Share app",
          // "19":"Rate Us",
        }
      };
}
